#!/bin/bash
set -euo pipefail

export typo3DatabaseName=test
export typo3DatabaseHost=db
export typo3DatabaseUsername=root
export typo3DatabasePassword=root
export typo3DatabasePort=3306
export typo3DatabaseDriver=mysqli

vendor/bin/phpunit -c Tests/FunctionalTests.xml
