name: pw-teaser
type: php
docroot: ""
php_version: "8.2"
composer_version: "2"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames:
    - v13.pw-teaser
use_dns_when_possible: true
web_environment:
    - EXTENSION_KEY=pw_teaser
    - PACKAGE_NAME=t3/pw_teaser
